version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: dev-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: oauth
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypass
    volumes:
        - mysql-data:/var/lib/mysql
    networks:
        - backend

volumes:
  mysql-data:

networks:
  backend: